INSERT INTO `bad_words` (id, word, replacement) VALUES (0, 'ahole ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (1, 'anus ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (2, 'ash0le ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (3, 'ash0les ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (4, 'asholes ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (5, 'ass ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (6, 'Ass Monkey ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (7, 'Assface ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (8, 'assh0le ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (9, 'assh0lez ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (10, 'asshole ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (11, 'assholes ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (12, 'assholz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (13, 'asswipe ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (14, 'azzhole ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (15, 'bassterds ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (16, 'bastard ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (17, 'bastards ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (18, 'bastardz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (19, 'basterds ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (20, 'basterdz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (21, 'Biatch ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (22, 'bitch ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (23, 'bitches ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (24, 'Blow Job ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (25, 'boffing ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (26, 'butthole ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (27, 'buttwipe ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (28, 'c0ck ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (29, 'c0cks ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (30, 'c0k ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (31, 'Carpet Muncher ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (32, 'cawk ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (33, 'cawks ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (34, 'Clit ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (35, 'cnts ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (36, 'cntz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (37, 'cock ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (38, 'cockhead ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (39, 'cock-head ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (40, 'cocks ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (41, 'CockSucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (42, 'cock-sucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (43, 'crap ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (44, 'cum ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (45, 'cunt ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (46, 'cunts ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (47, 'cuntz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (48, 'dick ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (49, 'dild0 ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (50, 'dild0s ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (51, 'dildo ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (52, 'dildos ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (53, 'dilld0 ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (54, 'dilld0s ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (55, 'dominatricks ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (56, 'dominatrics ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (57, 'dominatrix ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (58, 'dyke ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (59, 'enema ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (60, 'f u c k ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (61, 'f u c k e r ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (62, 'fag ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (63, 'fag1t ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (64, 'faget ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (65, 'fagg1t ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (66, 'faggit ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (67, 'faggot ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (68, 'fagit ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (69, 'fags ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (70, 'fagz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (71, 'faig ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (72, 'faigs ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (73, 'fart ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (74, 'flipping the bird ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (75, 'fuck ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (76, 'fucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (77, 'fuckin ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (78, 'fucking ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (79, 'fucks ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (80, 'Fudge Packer ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (81, 'fuk ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (82, 'Fukah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (83, 'Fuken ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (84, 'fuker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (85, 'Fukin ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (86, 'Fukk ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (87, 'Fukkah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (88, 'Fukken ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (89, 'Fukker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (90, 'Fukkin ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (91, 'g00k ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (92, 'gay ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (93, 'gayboy ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (94, 'gaygirl ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (95, 'gays ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (96, 'gayz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (97, 'God-damned ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (98, 'h00r ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (99, 'h0ar ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (100, 'h0re ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (101, 'hells ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (102, 'hoar ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (103, 'hoor ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (104, 'hoore ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (105, 'jackoff ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (106, 'jap ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (107, 'japs ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (108, 'jerk-off ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (109, 'jisim ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (110, 'jiss ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (111, 'jizm ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (112, 'jizz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (113, 'knob ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (114, 'knobs ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (115, 'knobz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (116, 'kunt ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (117, 'kunts ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (118, 'kuntz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (119, 'Lesbian ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (120, 'Lezzian ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (121, 'Lipshits ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (122, 'Lipshitz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (123, 'masochist ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (124, 'masokist ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (125, 'massterbait ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (126, 'masstrbait ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (127, 'masstrbate ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (128, 'masterbaiter ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (129, 'masterbate ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (130, 'masterbates ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (131, 'Motha Fucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (132, 'Motha Fuker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (133, 'Motha Fukkah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (134, 'Motha Fukker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (135, 'Mother Fucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (136, 'Mother Fukah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (137, 'Mother Fuker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (138, 'Mother Fukkah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (139, 'Mother Fukker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (140, 'mother-fucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (141, 'Mutha Fucker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (142, 'Mutha Fukah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (143, 'Mutha Fuker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (144, 'Mutha Fukkah ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (145, 'Mutha Fukker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (146, 'n1gr ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (147, 'nastt ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (148, 'nigger; ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (149, 'nigur; ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (150, 'niiger; ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (151, 'niigr; ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (152, 'orafis ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (153, 'orgasim; ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (154, 'orgasm ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (155, 'orgasum ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (156, 'oriface ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (157, 'orifice ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (158, 'orifiss ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (159, 'packi ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (160, 'packie ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (161, 'packy ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (162, 'paki ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (163, 'pakie ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (164, 'paky ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (165, 'pecker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (166, 'peeenus ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (167, 'peeenusss ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (168, 'peenus ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (169, 'peinus ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (170, 'pen1s ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (171, 'penas ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (172, 'penis ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (173, 'penis-breath ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (174, 'penus ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (175, 'penuus ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (176, 'Phuc ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (177, 'Phuck ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (178, 'Phuk ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (179, 'Phuker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (180, 'Phukker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (181, 'polac ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (182, 'polack ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (183, 'polak ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (184, 'Poonani ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (185, 'pr1c ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (186, 'pr1ck ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (187, 'pr1k ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (188, 'pusse ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (189, 'pussee ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (190, 'pussy ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (191, 'puuke ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (192, 'puuker ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (193, 'queer ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (194, 'queers ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (195, 'queerz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (196, 'qweers ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (197, 'qweerz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (198, 'qweir ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (199, 'recktum ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (200, 'rectum ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (201, 'retard ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (202, 'sadist ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (203, 'scank ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (204, 'schlong ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (205, 'screwing ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (206, 'semen ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (207, 'sex ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (208, 'sexy ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (209, 'Sh!t ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (210, 'sh1t ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (211, 'sh1ter ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (212, 'sh1ts ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (213, 'sh1tter ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (214, 'sh1tz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (215, 'shit ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (216, 'shits ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (217, 'shitter ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (218, 'Shitty ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (219, 'Shity ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (220, 'shitz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (221, 'Shyt ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (222, 'Shyte ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (223, 'Shytty ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (224, 'Shyty ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (225, 'skanck ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (226, 'skank ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (227, 'skankee ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (228, 'skankey ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (229, 'skanks ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (230, 'Skanky ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (231, 'slut ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (232, 'sluts ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (233, 'Slutty ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (234, 'slutz ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (235, 'son-of-a-bitch ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (236, 'tit ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (237, 'turd ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (238, 'va1jina ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (239, 'vag1na ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (240, 'vagiina ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (241, 'vagina ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (242, 'vaj1na ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (243, 'vajina ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (244, 'vullva ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (245, 'vulva ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (246, 'w0p ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (247, 'wh00r ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (248, 'wh0re ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (249, 'whore ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (250, 'xrated ', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (251, 'xxx', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (252, 'b!+ch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (253, 'bitch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (254, 'blowjob', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (255, 'clit', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (256, 'arschloch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (257, 'fuck', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (258, 'shit', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (259, 'ass', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (260, 'asshole', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (261, 'b!tch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (262, 'b17ch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (263, 'b1tch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (264, 'bastard', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (265, 'bi+ch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (266, 'boiolas', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (267, 'buceta', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (268, 'c0ck', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (269, 'cawk', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (270, 'chink', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (271, 'cipa', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (272, 'clits', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (273, 'cock', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (274, 'cum', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (275, 'cunt', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (276, 'dildo', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (277, 'dirsa', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (278, 'ejakulate', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (279, 'fatass', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (280, 'fcuk', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (281, 'fuk', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (282, 'fux0r', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (283, 'hoer', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (284, 'hore', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (285, 'jism', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (286, 'kawk', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (287, 'l3itch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (288, 'l3i+ch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (289, 'lesbian', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (290, 'masturbate', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (291, 'masterbat*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (292, 'masterbat3', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (293, 'motherfucker', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (294, 's.o.b.', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (295, 'mofo', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (296, 'nazi', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (297, 'nigga', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (298, 'nigger', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (299, 'nutsack', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (300, 'phuck', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (301, 'pimpis', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (302, 'pusse', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (303, 'pussy', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (304, 'scrotum', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (305, 'sh!t', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (306, 'shemale', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (307, 'shi+', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (308, 'sh!+', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (309, 'slut', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (310, 'smut', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (311, 'teets', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (312, 'tits', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (313, 'boobs', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (314, 'b00bs', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (315, 'teez', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (316, 'testical', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (317, 'testicle', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (318, 'titt', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (319, 'w00se', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (320, 'jackoff', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (321, 'wank', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (322, 'whoar', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (323, 'whore', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (324, '*damn', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (325, '*dyke', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (326, '*fuck*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (327, '*shit*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (328, '@$$', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (329, 'amcik', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (330, 'andskota', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (331, 'arse*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (332, 'assrammer', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (333, 'ayir', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (334, 'bi7ch', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (335, 'bitch*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (336, 'bollock*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (337, 'breasts', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (338, 'butt-pirate', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (339, 'cabron', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (340, 'cazzo', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (341, 'chraa', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (342, 'chuj', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (343, 'Cock*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (344, 'cunt*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (345, 'd4mn', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (346, 'daygo', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (347, 'dego', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (348, 'dick*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (349, 'dike*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (350, 'dupa', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (351, 'dziwka', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (352, 'ejackulate', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (353, 'Ekrem*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (354, 'Ekto', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (355, 'enculer', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (356, 'faen', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (357, 'fag*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (358, 'fanculo', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (359, 'fanny', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (360, 'feces', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (361, 'feg', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (362, 'Felcher', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (363, 'ficken', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (364, 'fitt*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (365, 'Flikker', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (366, 'foreskin', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (367, 'Fotze', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (368, 'Fu(*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (369, 'fuk*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (370, 'futkretzn', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (371, 'gay', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (372, 'gook', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (373, 'guiena', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (374, 'h0r', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (375, 'h4x0r', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (376, 'hell', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (377, 'helvete', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (378, 'hoer*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (379, 'honkey', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (380, 'Huevon', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (381, 'hui', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (382, 'injun', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (383, 'jizz', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (384, 'kanker*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (385, 'kike', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (386, 'klootzak', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (387, 'kraut', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (388, 'knulle', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (389, 'kuk', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (390, 'kuksuger', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (391, 'Kurac', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (392, 'kurwa', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (393, 'kusi*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (394, 'kyrpa*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (395, 'lesbo', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (396, 'mamhoon', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (397, 'masturbat*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (398, 'merd*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (399, 'mibun', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (400, 'monkleigh', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (401, 'mouliewop', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (402, 'muie', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (403, 'mulkku', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (404, 'muschi', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (405, 'nazis', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (406, 'nepesaurio', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (407, 'nigger*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (408, 'orospu', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (409, 'paska*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (410, 'perse', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (411, 'picka', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (412, 'pierdol*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (413, 'pillu*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (414, 'pimmel', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (415, 'piss*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (416, 'pizda', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (417, 'poontsee', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (418, 'poop', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (419, 'porn', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (420, 'p0rn', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (421, 'pr0n', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (422, 'preteen', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (423, 'pula', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (424, 'pule', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (425, 'puta', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (426, 'puto', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (427, 'qahbeh', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (428, 'queef*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (429, 'rautenberg', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (430, 'schaffer', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (431, 'scheiss*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (432, 'schlampe', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (433, 'schmuck', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (434, 'screw', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (435, 'sh!t*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (436, 'sharmuta', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (437, 'sharmute', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (438, 'shipal', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (439, 'shiz', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (440, 'skribz', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (441, 'skurwysyn', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (442, 'sphencter', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (443, 'spic', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (444, 'spierdalaj', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (445, 'splooge', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (446, 'suka', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (447, 'b00b*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (448, 'testicle*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (449, 'titt*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (450, 'twat', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (451, 'vittu', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (452, 'wank*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (453, 'wetback*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (454, 'wichser', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (455, 'wop*', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (456, 'yed', '[censored]');
INSERT INTO `bad_words` (id, word, replacement) VALUES (457, 'zabourah', '[censored]');